### ISSUE TITLE
GPG error: http://deb.debian.org/debian bullseye InRelease: At least one invalid signature was encountered.

### ISSUE THREAD

**Issue by ozbillwang** [dotnet/dotnet-docker#4367]
### Describe the Bug

can't run `apt-get update` in this image

### Steps to Reproduce

```
docker run -ti --rm mcr.microsoft.com/dotnet/sdk:6.0 bash
root@1199c3ae471c:/# apt update
Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Err:1 http://deb.debian.org/debian bullseye InRelease
  At least one invalid signature was encountered.
Err:2 http://deb.debian.org/debian-security bullseye-security InRelease
  At least one invalid signature was encountered.
Err:3 http://deb.debian.org/debian bullseye-updates InRelease
  At least one invalid signature was encountered.
Reading package lists... Done
W: GPG error: http://deb.debian.org/debian bullseye InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian bullseye InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://deb.debian.org/debian-security bullseye-security InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian-security bullseye-security InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://deb.debian.org/debian bullseye-updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian bullseye-updates InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
### Other Information

The image `mcr.microsoft.com/dotnet/sdk:6.0` is fine to run with `apt-get update`, check in https://mcr.microsoft.com/en-us/product/dotnet/sdk/tags, seems the tag `6.0` was updated on 11th Jan 2023

![image](https://user-images.githubusercontent.com/8954908/215488008-b2d09bec-fa4f-4aa6-a48a-438f9c6d5790.png)

### Output of `docker version`

```
 docker version
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/amd64
 Context:           colima
 Experimental:      true

Server:
 Engine:
  Version:          20.10.18
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.6
  Git commit:       e42327a6d3c55ceda3bd5475be7aae6036d02db3
  Built:            Sun Sep 11 07:10:00 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        5fd4c4d144137e991c4acebb2146ab1483a97925
 docker-init:
  Version:          0.19.0
  GitCommit:
```

**Comment by mthalman** [comment]
Can you try checking again? I just tried and it works for me. This error can happen the Debian package mirror is having issues and typically is resolved after a period of time. It's unrelated to the actual image but rather with the package service itself.

**Comment by ozbillwang** [comment]
@mthalman 

Thanks for helping me. 

I run the tests again, still get the same issue

![image](https://user-images.githubusercontent.com/8954908/215623337-6eeb39a4-22f7-481f-b31f-b1c4f092f622.png)

I run it from my laptop (no proxy required to internet).

**Comment by richlander** [comment]
Works for me.

```bash
$ docker images | grep sdk
mcr.microsoft.com/dotnet/sdk                        6.0                             a7ec5e623ff0   8 hours ago     738MB
$ docker run -ti --rm mcr.microsoft.com/dotnet/sdk:6.0 apt update
Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8183 kB]
Get:5 http://deb.debian.org/debian-security bullseye-security/main amd64 Packages [218 kB]
Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [14.6 kB]
Fetched 8624 kB in 2s (3909 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
```

**Comment by ozbillwang** [comment]
this is the image I got yesterday. 
```
mcr.microsoft.com/dotnet/sdk                                        6.0               6a9a891a94b3   2 weeks ago    738MB
```
today I pull again, get different hashkey

```
mcr.microsoft.com/dotnet/sdk                                        6.0               a7ec5e623ff0   8 hours ago    738MB
```

But both have same issue.

**Comment by richlander** [comment]
Try it on a different network? Almost seems like your requests are being intercepted.

**Comment by ozbillwang** [comment]
sure, will update later.

**Comment by ozbillwang** [comment]
So it is only in my environment. 

dotnet image is built based on debian image. I run `apt update`, got same error. 

![image](https://user-images.githubusercontent.com/8954908/215956841-0cd2075c-ca3a-4eea-89ed-c7fb1bdcec03.png)

But still not sure what's the problem , why on my laptop.
